<?php
/**
 *
 * Please refer to the documentation @ http://docs.whmcs.com/Hooks for more information
 *
 * @package    WHMCS Add Invoice Activity to LeadDyno
 * @author     Eric Baker <eric@ericbaker.me>
 * @copyright  GPLv2 (or later)
 * @license    http://www.fsf.org/
 * @version    0.1.0
 * @link       http://www.gowp.com/
 */

if (!defined("WHMCS"))
    die("This file cannot be accessed directly");

// Let's set this here since everyone will want access to it.
$GLOBALS['leaddyno_key'] = '';

add_hook('InvoicePaid', 1, function($vars) {
	// $vars['invoiceid'] is the only var passed into this hook.
	
	// 1. Get the invoice information from WHMCS
	function get_invoice_info($invoice_id) {
		//Define the paramaters
		$command = 'GetInvoice';
		$values = array(
			'invoiceid' => $invoice_id
		);
		$adminUsername = 'admin';

		// Call the Local API
		$invoice_info = localAPI($command, $postData, $adminUsername);

		// Make it an object
		return json_decode($invoice_info);
	}
	
	// 2. Get the Client email from WHMCS
	function get_client_email($client_id) {
		//Define the paramaters
		$command = 'GetClientDetails';
		$values = array(
			'clientid' => $client_id,
			'stats' => false,
		);
		$adminUsername = 'admin';

		// Call the local API
		$client_info = localAPI($command, $postData, $adminUsername);

		//Make it pretty
		$client_array = json_decode($client_info, true);
		return $client_array['client[email]'];
	}
	
    // 3. Create LeadDyno Purchase
	function create_leaddyno_purchase($vars){
	    $invoiceinfo = get_invoice_info($vars['invoiceid']);
	    $clientemail = get_client_email($invoiceinfo->userid);
	
		// Gather all the info for the curl request
		$url = 'https://api.leaddyno.com/v1/purchases';
		$req = '&email=' . $clientemail;
		$req .= '&purchase_amount=' . $invoiceinfo->total;
		
		// Actually make the curl request
		make_curl_request( $url, $req );
	}

	// 4. Get the Client info from WHMCS
	function get_client_info($client_id) {
		//Define the paramaters
		$command = 'GetClientDetails';
		$values = array(
			'clientid' => $client_id,
			'stats' => false,
		);
		$adminUsername = 'admin';

		// Call the local API
		$client_info = localAPI($command, $postData, $adminUsername);

		//Make it pretty
		$client_array = json_decode($client_info, true);
		return $client_array;
	}

	// 5. Create a LeadDyno affiliate. If they already exists, it ignores our request
	function create_a_leaddyno_affiliate($vars){
		$clientinfo = get_client_info(get_invoice_info($vars['invoiceid'])->userid);

		// Gather the children for the trip
		$url = 'https://api.leaddyno.com/v1/affiliates';
		$req = '&email=' . $clientinfo['client[email]'];
		$req .= '&first_name=' . $clientinfo['client[firstname]'];
		$req .= '&last_name=' . $clientinfo['client[lastname]']

		// Send the children on the trip
		make_curl_request($url, $req);
	}

	$create_purchase = create_leaddyno_purchase($vars);
	if ($create_purchase) { create_a_leaddyno_affiliate($vars); }

});

add_hook('InvoiceRefunded', 1, function($vars) {
    // Perform hook code here...
});

// This is the function that does the stuffs for everybody
function make_curl_request( $url, $args ) {
	$post_fields = 'key=' . $GLOBALS['leaddyno_key'];
	$post_fields .= $args;

    // The framework was generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();
    
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    
    curl_setopt($ch, CURLOPT_POSTFIELDS, $post_fields);
    curl_setopt($ch, CURLOPT_POST, 1);
    
    // Set the Headers to authorize the request and accept json
    $headers   = array();
    $headers[] = "Content-Type: application/x-www-form-urlencoded";
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    
    // Execute the request
    $result = curl_exec($ch);
    
    // Error handling
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    
    // Close the request
    curl_close($ch);
}